//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Account
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Account.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account activated.
        /// </summary>
        public static string AccountActivated {
            get {
                return ResourceManager.GetString("AccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access your account?.
        /// </summary>
        public static string CanNotAccessYourAccount {
            get {
                return ResourceManager.GetString("CanNotAccessYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset the password associated with this e-mail address. If you made this request, please follow the instructions below.
        ///
        ///Click the link below to reset your password using our secure server:
        ///
        ///{0}
        ///
        ///If you did not request to have your password reset you can safely ignore this email. Rest assured your customer account is safe.
        ///
        ///If clicking the link doesn&apos;t seem to work, you can copy and paste the link into your browser&apos;s address window, or retype it there. Once you have returned [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CantAccessYourAccount_Email {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found mathing the email address provided.
        /// </summary>
        public static string CantAccessYourAccount_EmailNotFound {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to the email address provided.
        /// </summary>
        public static string CantAccessYourAccount_EmailSent {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Password Assistance.
        /// </summary>
        public static string CantAccessYourAccount_EmailTitle {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed.
        /// </summary>
        public static string CantAccessYourAccount_PasswordChanged {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has expired and you need to start process in order to change your password.
        /// </summary>
        public static string CantAccessYourAccount_TokenExpired {
            get {
                return ResourceManager.GetString("CantAccessYourAccount_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for visiting {0}! Per your request, we have successfully changed your password..
        /// </summary>
        public static string ChangePassword_EmailBody {
            get {
                return ResourceManager.GetString("ChangePassword_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision to your {0} Account.
        /// </summary>
        public static string ChangePassword_EmailTitle {
            get {
                return ResourceManager.GetString("ChangePassword_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}. To activate {0} you must first verify your email address by clicking the link below:
        ///
        ///{1}
        ///  
        ///If clicking the link above does not work, copy and paste the URL in a new browser window instead.
        ///
        ///If you believe that you have received this email in error, just do nothing.
        ///
        ///Thank you for choosing {0} as your cloud based file sharing service provider.
        ///
        ///Sincerely, Your {0} Support Team.
        /// </summary>
        public static string CreateNewAccount_EmailBody {
            get {
                return ResourceManager.GetString("CreateNewAccount_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to the email address provided. Please, activate your account.
        /// </summary>
        public static string CreateNewAccount_EmailSent {
            get {
                return ResourceManager.GetString("CreateNewAccount_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Email Verification.
        /// </summary>
        public static string CreateNewAccount_EmailSubject {
            get {
                return ResourceManager.GetString("CreateNewAccount_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account.
        /// </summary>
        public static string IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match.
        /// </summary>
        public static string NewPasswordConfirmError {
            get {
                return ResourceManager.GetString("NewPasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be changed.
        /// </summary>
        public static string PasswordCouldNotBeChanged {
            get {
                return ResourceManager.GetString("PasswordCouldNotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length.
        /// </summary>
        public static string PasswordRequireToHaveXCharsLength {
            get {
                return ResourceManager.GetString("PasswordRequireToHaveXCharsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        public static string PleaseEnterYourUsernameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string ProfileView {
            get {
                return ResourceManager.GetString("ProfileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in your form, see details below.
        /// </summary>
        public static string ThereAreErrorsInForm_SeeDetails {
            get {
                return ResourceManager.GetString("ThereAreErrorsInForm_SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, type the full email address you use to sign in..
        /// </summary>
        public static string ToResetYourPassword {
            get {
                return ResourceManager.GetString("ToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account.
        /// </summary>
        public static string UserFormBelowToCreateAccount {
            get {
                return ResourceManager.GetString("UserFormBelowToCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string UserNameOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
