

// This file was generated by build event calling 'ResourceBuildEventPre.cmd' which executes T4 template 'ResourceBuildEventPre.tt' 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using $safeprojectname$.Account;
using $safeprojectname$.Blog;
using $safeprojectname$.DataAnnotations;
using $safeprojectname$.Enumerations;
using $safeprojectname$.General;
using $safeprojectname$.Javascript;
using $safeprojectname$.UserAdministration;
using $safeprojectname$.UserProfile;

namespace $safeprojectname$.Helpers.GeneratedResxClasses
{
	public class AccountResourcesKeys
	{
		public const String AccountActivated = "AccountActivated";
		public const String AccountInformation = "AccountInformation";
		public const String CanNotAccessYourAccount = "CanNotAccessYourAccount";
		public const String CantAccessYourAccount_Email = "CantAccessYourAccount_Email";
		public const String CantAccessYourAccount_EmailNotFound = "CantAccessYourAccount_EmailNotFound";
		public const String CantAccessYourAccount_EmailSent = "CantAccessYourAccount_EmailSent";
		public const String CantAccessYourAccount_EmailTitle = "CantAccessYourAccount_EmailTitle";
		public const String CantAccessYourAccount_PasswordChanged = "CantAccessYourAccount_PasswordChanged";
		public const String CantAccessYourAccount_TokenExpired = "CantAccessYourAccount_TokenExpired";
		public const String ChangePassword = "ChangePassword";
		public const String ChangePassword_EmailBody = "ChangePassword_EmailBody";
		public const String ChangePassword_EmailTitle = "ChangePassword_EmailTitle";
		public const String ConfirmPassword = "ConfirmPassword";
		public const String CreateNewAccount = "CreateNewAccount";
		public const String CreateNewAccount_EmailBody = "CreateNewAccount_EmailBody";
		public const String CreateNewAccount_EmailSent = "CreateNewAccount_EmailSent";
		public const String CreateNewAccount_EmailSubject = "CreateNewAccount_EmailSubject";
		public const String Email = "Email";
		public const String EmailAddress = "EmailAddress";
		public const String ForgotPasswordQuestion = "ForgotPasswordQuestion";
		public const String IfYouDontHaveAnAccount = "IfYouDontHaveAnAccount";
		public const String InvalidPassword = "InvalidPassword";
		public const String LogOn = "LogOn";
		public const String NewPassword = "NewPassword";
		public const String NewPasswordConfirm = "NewPasswordConfirm";
		public const String NewPasswordConfirmError = "NewPasswordConfirmError";
		public const String OldPassword = "OldPassword";
		public const String Password = "Password";
		public const String PasswordCouldNotBeChanged = "PasswordCouldNotBeChanged";
		public const String PasswordRequireToHaveXCharsLength = "PasswordRequireToHaveXCharsLength";
		public const String PleaseEnterYourUsernameAndPassword = "PleaseEnterYourUsernameAndPassword";
		public const String ProfileEdit = "ProfileEdit";
		public const String ProfileView = "ProfileView";
		public const String Register = "Register";
		public const String RememberMe = "RememberMe";
		public const String Send = "Send";
		public const String SignIn = "SignIn";
		public const String SignOut = "SignOut";
		public const String ThereAreErrorsInForm_SeeDetails = "ThereAreErrorsInForm_SeeDetails";
		public const String ToResetYourPassword = "ToResetYourPassword";
		public const String UserFormBelowToCreateAccount = "UserFormBelowToCreateAccount";
		public const String UserName = "UserName";
		public const String UserNameOrPasswordInvalid = "UserNameOrPasswordInvalid";
		public const String UserProfile = "UserProfile";
	}
	public class AccountResourcesViewModelHelper
	{
		public  string AccountActivated {	get{	return AccountResources.AccountActivated;	}	}
		public  string AccountInformation {	get{	return AccountResources.AccountInformation;	}	}
		public  string CanNotAccessYourAccount {	get{	return AccountResources.CanNotAccessYourAccount;	}	}
		public  string CantAccessYourAccount_Email {	get{	return AccountResources.CantAccessYourAccount_Email;	}	}
		public  string CantAccessYourAccount_EmailNotFound {	get{	return AccountResources.CantAccessYourAccount_EmailNotFound;	}	}
		public  string CantAccessYourAccount_EmailSent {	get{	return AccountResources.CantAccessYourAccount_EmailSent;	}	}
		public  string CantAccessYourAccount_EmailTitle {	get{	return AccountResources.CantAccessYourAccount_EmailTitle;	}	}
		public  string CantAccessYourAccount_PasswordChanged {	get{	return AccountResources.CantAccessYourAccount_PasswordChanged;	}	}
		public  string CantAccessYourAccount_TokenExpired {	get{	return AccountResources.CantAccessYourAccount_TokenExpired;	}	}
		public  string ChangePassword {	get{	return AccountResources.ChangePassword;	}	}
		public  string ChangePassword_EmailBody {	get{	return AccountResources.ChangePassword_EmailBody;	}	}
		public  string ChangePassword_EmailTitle {	get{	return AccountResources.ChangePassword_EmailTitle;	}	}
		public  string ConfirmPassword {	get{	return AccountResources.ConfirmPassword;	}	}
		public  string CreateNewAccount {	get{	return AccountResources.CreateNewAccount;	}	}
		public  string CreateNewAccount_EmailBody {	get{	return AccountResources.CreateNewAccount_EmailBody;	}	}
		public  string CreateNewAccount_EmailSent {	get{	return AccountResources.CreateNewAccount_EmailSent;	}	}
		public  string CreateNewAccount_EmailSubject {	get{	return AccountResources.CreateNewAccount_EmailSubject;	}	}
		public  string Email {	get{	return AccountResources.Email;	}	}
		public  string EmailAddress {	get{	return AccountResources.EmailAddress;	}	}
		public  string ForgotPasswordQuestion {	get{	return AccountResources.ForgotPasswordQuestion;	}	}
		public  string IfYouDontHaveAnAccount {	get{	return AccountResources.IfYouDontHaveAnAccount;	}	}
		public  string InvalidPassword {	get{	return AccountResources.InvalidPassword;	}	}
		public  string LogOn {	get{	return AccountResources.LogOn;	}	}
		public  string NewPassword {	get{	return AccountResources.NewPassword;	}	}
		public  string NewPasswordConfirm {	get{	return AccountResources.NewPasswordConfirm;	}	}
		public  string NewPasswordConfirmError {	get{	return AccountResources.NewPasswordConfirmError;	}	}
		public  string OldPassword {	get{	return AccountResources.OldPassword;	}	}
		public  string Password {	get{	return AccountResources.Password;	}	}
		public  string PasswordCouldNotBeChanged {	get{	return AccountResources.PasswordCouldNotBeChanged;	}	}
		public  string PasswordRequireToHaveXCharsLength {	get{	return AccountResources.PasswordRequireToHaveXCharsLength;	}	}
		public  string PleaseEnterYourUsernameAndPassword {	get{	return AccountResources.PleaseEnterYourUsernameAndPassword;	}	}
		public  string ProfileEdit {	get{	return AccountResources.ProfileEdit;	}	}
		public  string ProfileView {	get{	return AccountResources.ProfileView;	}	}
		public  string Register {	get{	return AccountResources.Register;	}	}
		public  string RememberMe {	get{	return AccountResources.RememberMe;	}	}
		public  string Send {	get{	return AccountResources.Send;	}	}
		public  string SignIn {	get{	return AccountResources.SignIn;	}	}
		public  string SignOut {	get{	return AccountResources.SignOut;	}	}
		public  string ThereAreErrorsInForm_SeeDetails {	get{	return AccountResources.ThereAreErrorsInForm_SeeDetails;	}	}
		public  string ToResetYourPassword {	get{	return AccountResources.ToResetYourPassword;	}	}
		public  string UserFormBelowToCreateAccount {	get{	return AccountResources.UserFormBelowToCreateAccount;	}	}
		public  string UserName {	get{	return AccountResources.UserName;	}	}
		public  string UserNameOrPasswordInvalid {	get{	return AccountResources.UserNameOrPasswordInvalid;	}	}
		public  string UserProfile {	get{	return AccountResources.UserProfile;	}	}
	}
	public class BlogTextsKeys
	{
		public const String BrowseBy = "BrowseBy";
		public const String Category = "Category";
		public const String PublishDate = "PublishDate";
	}
	public class BlogTextsViewModelHelper
	{
		public  string BrowseBy {	get{	return BlogTexts.BrowseBy;	}	}
		public  string Category {	get{	return BlogTexts.Category;	}	}
		public  string PublishDate {	get{	return BlogTexts.PublishDate;	}	}
	}
	public class DataAnnotationsResourcesKeys
	{
		public const String BindingBehavior_ValueNotFound = "BindingBehavior_ValueNotFound";
		public const String ChildActionCacheAttribute_DurationMustBePositive = "ChildActionCacheAttribute_DurationMustBePositive";
		public const String CommonControls_NameRequired = "CommonControls_NameRequired";
		public const String Common_ModelBinderDoesNotSupportModelType = "Common_ModelBinderDoesNotSupportModelType";
		public const String Common_NullOrEmpty = "Common_NullOrEmpty";
		public const String Common_PropertyNotFound = "Common_PropertyNotFound";
		public const String Common_TypeMustImplementInterface = "Common_TypeMustImplementInterface";
		public const String CompareAttribute_MustMatch = "CompareAttribute_MustMatch";
		public const String CompareAttribute_UnknownProperty = "CompareAttribute_UnknownProperty";
		public const String ControllerBuilder_FactoryReturnedNull = "ControllerBuilder_FactoryReturnedNull";
		public const String CreditCardAttribute_Invalid = "CreditCardAttribute_Invalid";
		public const String DataAnnotationsModelMetadataProvider_UnknownProperty = "DataAnnotationsModelMetadataProvider_UnknownProperty";
		public const String DataAnnotationsModelMetadataProvider_UnreadableProperty = "DataAnnotationsModelMetadataProvider_UnreadableProperty";
		public const String DateAttribute_Invalid = "DateAttribute_Invalid";
		public const String DateMustBeGreaterThan = "DateMustBeGreaterThan";
		public const String DateMustBeLowerThan = "DateMustBeLowerThan";
		public const String DigitsAttribute_Invalid = "DigitsAttribute_Invalid";
		public const String DropDownList_SampleItem = "DropDownList_SampleItem";
		public const String DynamicViewDataDictionary_SingleIndexerOnly = "DynamicViewDataDictionary_SingleIndexerOnly";
		public const String DynamicViewDataDictionary_StringIndexerOnly = "DynamicViewDataDictionary_StringIndexerOnly";
		public const String DynamicViewPage_NoProperties = "DynamicViewPage_NoProperties";
		public const String DynamicViewPage_PropertyDoesNotExist = "DynamicViewPage_PropertyDoesNotExist";
		public const String EmailAddressAttribute_Invalid = "EmailAddressAttribute_Invalid";
		public const String EmailNotValid = "EmailNotValid";
		public const String EqualTo_UnknownProperty = "EqualTo_UnknownProperty";
		public const String ExpressionHelper_CannotCallCompletedMethod = "ExpressionHelper_CannotCallCompletedMethod";
		public const String ExpressionHelper_CannotCallNonAction = "ExpressionHelper_CannotCallNonAction";
		public const String ExpressionHelper_CannotRouteToController = "ExpressionHelper_CannotRouteToController";
		public const String ExpressionHelper_MustBeMethodCall = "ExpressionHelper_MustBeMethodCall";
		public const String ExpressionHelper_TargetMustEndInController = "ExpressionHelper_TargetMustEndInController";
		public const String ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet = "ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet";
		public const String FileExtensionsAttribute_Invalid = "FileExtensionsAttribute_Invalid";
		public const String GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType = "GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType";
		public const String GenericModelBinderProvider_TypeArgumentCountMismatch = "GenericModelBinderProvider_TypeArgumentCountMismatch";
		public const String HtmlHelper_MissingSelectData = "HtmlHelper_MissingSelectData";
		public const String HtmlHelper_WrongSelectDataType = "HtmlHelper_WrongSelectDataType";
		public const String IntegerAttribute_Invalid = "IntegerAttribute_Invalid";
		public const String MaxAttribute_Invalid = "MaxAttribute_Invalid";
		public const String MinAttribute_Invalid = "MinAttribute_Invalid";
		public const String ModelBinderConfig_ValueInvalid = "ModelBinderConfig_ValueInvalid";
		public const String ModelBinderConfig_ValueRequired = "ModelBinderConfig_ValueRequired";
		public const String ModelBinderProviderCollection_BinderForTypeNotFound = "ModelBinderProviderCollection_BinderForTypeNotFound";
		public const String ModelBinderProviderCollection_InvalidBinderType = "ModelBinderProviderCollection_InvalidBinderType";
		public const String ModelBinderProviderCollection_TypeCannotHaveBindAttribute = "ModelBinderProviderCollection_TypeCannotHaveBindAttribute";
		public const String ModelBinderUtil_ModelCannotBeNull = "ModelBinderUtil_ModelCannotBeNull";
		public const String ModelBinderUtil_ModelInstanceIsWrong = "ModelBinderUtil_ModelInstanceIsWrong";
		public const String ModelBinderUtil_ModelMetadataCannotBeNull = "ModelBinderUtil_ModelMetadataCannotBeNull";
		public const String ModelBinderUtil_ModelTypeIsWrong = "ModelBinderUtil_ModelTypeIsWrong";
		public const String ModelBindingContext_ModelMetadataMustBeSet = "ModelBindingContext_ModelMetadataMustBeSet";
		public const String MvcDynamicSessionModule_WrongControllerFactory = "MvcDynamicSessionModule_WrongControllerFactory";
		public const String MvcSerializer_DeserializationFailed = "MvcSerializer_DeserializationFailed";
		public const String MvcSerializer_InvalidSerializationMode = "MvcSerializer_InvalidSerializationMode";
		public const String MvcSerializer_MagicHeaderCheckFailed = "MvcSerializer_MagicHeaderCheckFailed";
		public const String NumericAttribute_Invalid = "NumericAttribute_Invalid";
		public const String ResourceControllerFactory_ConflictingActions = "ResourceControllerFactory_ConflictingActions";
		public const String ResourceControllerFactory_NoActions = "ResourceControllerFactory_NoActions";
		public const String Resources_UnsupportedFormat = "Resources_UnsupportedFormat";
		public const String Resources_UnsupportedMediaType = "Resources_UnsupportedMediaType";
		public const String StringLengthAttribute_Invalid = "StringLengthAttribute_Invalid";
		public const String UrlAttribute_Invalid = "UrlAttribute_Invalid";
	}
	public class DataAnnotationsResourcesViewModelHelper
	{
		public  string BindingBehavior_ValueNotFound {	get{	return DataAnnotationsResources.BindingBehavior_ValueNotFound;	}	}
		public  string ChildActionCacheAttribute_DurationMustBePositive {	get{	return DataAnnotationsResources.ChildActionCacheAttribute_DurationMustBePositive;	}	}
		public  string CommonControls_NameRequired {	get{	return DataAnnotationsResources.CommonControls_NameRequired;	}	}
		public  string Common_ModelBinderDoesNotSupportModelType {	get{	return DataAnnotationsResources.Common_ModelBinderDoesNotSupportModelType;	}	}
		public  string Common_NullOrEmpty {	get{	return DataAnnotationsResources.Common_NullOrEmpty;	}	}
		public  string Common_PropertyNotFound {	get{	return DataAnnotationsResources.Common_PropertyNotFound;	}	}
		public  string Common_TypeMustImplementInterface {	get{	return DataAnnotationsResources.Common_TypeMustImplementInterface;	}	}
		public  string CompareAttribute_MustMatch {	get{	return DataAnnotationsResources.CompareAttribute_MustMatch;	}	}
		public  string CompareAttribute_UnknownProperty {	get{	return DataAnnotationsResources.CompareAttribute_UnknownProperty;	}	}
		public  string ControllerBuilder_FactoryReturnedNull {	get{	return DataAnnotationsResources.ControllerBuilder_FactoryReturnedNull;	}	}
		public  string CreditCardAttribute_Invalid {	get{	return DataAnnotationsResources.CreditCardAttribute_Invalid;	}	}
		public  string DataAnnotationsModelMetadataProvider_UnknownProperty {	get{	return DataAnnotationsResources.DataAnnotationsModelMetadataProvider_UnknownProperty;	}	}
		public  string DataAnnotationsModelMetadataProvider_UnreadableProperty {	get{	return DataAnnotationsResources.DataAnnotationsModelMetadataProvider_UnreadableProperty;	}	}
		public  string DateAttribute_Invalid {	get{	return DataAnnotationsResources.DateAttribute_Invalid;	}	}
		public  string DateMustBeGreaterThan {	get{	return DataAnnotationsResources.DateMustBeGreaterThan;	}	}
		public  string DateMustBeLowerThan {	get{	return DataAnnotationsResources.DateMustBeLowerThan;	}	}
		public  string DigitsAttribute_Invalid {	get{	return DataAnnotationsResources.DigitsAttribute_Invalid;	}	}
		public  string DropDownList_SampleItem {	get{	return DataAnnotationsResources.DropDownList_SampleItem;	}	}
		public  string DynamicViewDataDictionary_SingleIndexerOnly {	get{	return DataAnnotationsResources.DynamicViewDataDictionary_SingleIndexerOnly;	}	}
		public  string DynamicViewDataDictionary_StringIndexerOnly {	get{	return DataAnnotationsResources.DynamicViewDataDictionary_StringIndexerOnly;	}	}
		public  string DynamicViewPage_NoProperties {	get{	return DataAnnotationsResources.DynamicViewPage_NoProperties;	}	}
		public  string DynamicViewPage_PropertyDoesNotExist {	get{	return DataAnnotationsResources.DynamicViewPage_PropertyDoesNotExist;	}	}
		public  string EmailAddressAttribute_Invalid {	get{	return DataAnnotationsResources.EmailAddressAttribute_Invalid;	}	}
		public  string EmailNotValid {	get{	return DataAnnotationsResources.EmailNotValid;	}	}
		public  string EqualTo_UnknownProperty {	get{	return DataAnnotationsResources.EqualTo_UnknownProperty;	}	}
		public  string ExpressionHelper_CannotCallCompletedMethod {	get{	return DataAnnotationsResources.ExpressionHelper_CannotCallCompletedMethod;	}	}
		public  string ExpressionHelper_CannotCallNonAction {	get{	return DataAnnotationsResources.ExpressionHelper_CannotCallNonAction;	}	}
		public  string ExpressionHelper_CannotRouteToController {	get{	return DataAnnotationsResources.ExpressionHelper_CannotRouteToController;	}	}
		public  string ExpressionHelper_MustBeMethodCall {	get{	return DataAnnotationsResources.ExpressionHelper_MustBeMethodCall;	}	}
		public  string ExpressionHelper_TargetMustEndInController {	get{	return DataAnnotationsResources.ExpressionHelper_TargetMustEndInController;	}	}
		public  string ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet {	get{	return DataAnnotationsResources.ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet;	}	}
		public  string FileExtensionsAttribute_Invalid {	get{	return DataAnnotationsResources.FileExtensionsAttribute_Invalid;	}	}
		public  string GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType {	get{	return DataAnnotationsResources.GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType;	}	}
		public  string GenericModelBinderProvider_TypeArgumentCountMismatch {	get{	return DataAnnotationsResources.GenericModelBinderProvider_TypeArgumentCountMismatch;	}	}
		public  string HtmlHelper_MissingSelectData {	get{	return DataAnnotationsResources.HtmlHelper_MissingSelectData;	}	}
		public  string HtmlHelper_WrongSelectDataType {	get{	return DataAnnotationsResources.HtmlHelper_WrongSelectDataType;	}	}
		public  string IntegerAttribute_Invalid {	get{	return DataAnnotationsResources.IntegerAttribute_Invalid;	}	}
		public  string MaxAttribute_Invalid {	get{	return DataAnnotationsResources.MaxAttribute_Invalid;	}	}
		public  string MinAttribute_Invalid {	get{	return DataAnnotationsResources.MinAttribute_Invalid;	}	}
		public  string ModelBinderConfig_ValueInvalid {	get{	return DataAnnotationsResources.ModelBinderConfig_ValueInvalid;	}	}
		public  string ModelBinderConfig_ValueRequired {	get{	return DataAnnotationsResources.ModelBinderConfig_ValueRequired;	}	}
		public  string ModelBinderProviderCollection_BinderForTypeNotFound {	get{	return DataAnnotationsResources.ModelBinderProviderCollection_BinderForTypeNotFound;	}	}
		public  string ModelBinderProviderCollection_InvalidBinderType {	get{	return DataAnnotationsResources.ModelBinderProviderCollection_InvalidBinderType;	}	}
		public  string ModelBinderProviderCollection_TypeCannotHaveBindAttribute {	get{	return DataAnnotationsResources.ModelBinderProviderCollection_TypeCannotHaveBindAttribute;	}	}
		public  string ModelBinderUtil_ModelCannotBeNull {	get{	return DataAnnotationsResources.ModelBinderUtil_ModelCannotBeNull;	}	}
		public  string ModelBinderUtil_ModelInstanceIsWrong {	get{	return DataAnnotationsResources.ModelBinderUtil_ModelInstanceIsWrong;	}	}
		public  string ModelBinderUtil_ModelMetadataCannotBeNull {	get{	return DataAnnotationsResources.ModelBinderUtil_ModelMetadataCannotBeNull;	}	}
		public  string ModelBinderUtil_ModelTypeIsWrong {	get{	return DataAnnotationsResources.ModelBinderUtil_ModelTypeIsWrong;	}	}
		public  string ModelBindingContext_ModelMetadataMustBeSet {	get{	return DataAnnotationsResources.ModelBindingContext_ModelMetadataMustBeSet;	}	}
		public  string MvcDynamicSessionModule_WrongControllerFactory {	get{	return DataAnnotationsResources.MvcDynamicSessionModule_WrongControllerFactory;	}	}
		public  string MvcSerializer_DeserializationFailed {	get{	return DataAnnotationsResources.MvcSerializer_DeserializationFailed;	}	}
		public  string MvcSerializer_InvalidSerializationMode {	get{	return DataAnnotationsResources.MvcSerializer_InvalidSerializationMode;	}	}
		public  string MvcSerializer_MagicHeaderCheckFailed {	get{	return DataAnnotationsResources.MvcSerializer_MagicHeaderCheckFailed;	}	}
		public  string NumericAttribute_Invalid {	get{	return DataAnnotationsResources.NumericAttribute_Invalid;	}	}
		public  string ResourceControllerFactory_ConflictingActions {	get{	return DataAnnotationsResources.ResourceControllerFactory_ConflictingActions;	}	}
		public  string ResourceControllerFactory_NoActions {	get{	return DataAnnotationsResources.ResourceControllerFactory_NoActions;	}	}
		public  string Resources_UnsupportedFormat {	get{	return DataAnnotationsResources.Resources_UnsupportedFormat;	}	}
		public  string Resources_UnsupportedMediaType {	get{	return DataAnnotationsResources.Resources_UnsupportedMediaType;	}	}
		public  string StringLengthAttribute_Invalid {	get{	return DataAnnotationsResources.StringLengthAttribute_Invalid;	}	}
		public  string UrlAttribute_Invalid {	get{	return DataAnnotationsResources.UrlAttribute_Invalid;	}	}
	}
	public class EnumerationsTextsKeys
	{
		public const String Template_Models_Enumerations_ThemesAvailable_Base = "Template_Models_Enumerations_ThemesAvailable_Base";
		public const String Template_Models_Enumerations_ThemesAvailable_Black_Tie = "Template_Models_Enumerations_ThemesAvailable_Black_Tie";
		public const String Template_Models_Enumerations_ThemesAvailable_Blitzer = "Template_Models_Enumerations_ThemesAvailable_Blitzer";
		public const String Template_Models_Enumerations_ThemesAvailable_Cupertino = "Template_Models_Enumerations_ThemesAvailable_Cupertino";
		public const String Template_Models_Enumerations_ThemesAvailable_Dark_Hive = "Template_Models_Enumerations_ThemesAvailable_Dark_Hive";
		public const String Template_Models_Enumerations_ThemesAvailable_Dot_Luv = "Template_Models_Enumerations_ThemesAvailable_Dot_Luv";
		public const String Template_Models_Enumerations_ThemesAvailable_Eggplant = "Template_Models_Enumerations_ThemesAvailable_Eggplant";
		public const String Template_Models_Enumerations_ThemesAvailable_Excite_Bike = "Template_Models_Enumerations_ThemesAvailable_Excite_Bike";
		public const String Template_Models_Enumerations_ThemesAvailable_Flick = "Template_Models_Enumerations_ThemesAvailable_Flick";
		public const String Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks = "Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks";
		public const String Template_Models_Enumerations_ThemesAvailable_Humanity = "Template_Models_Enumerations_ThemesAvailable_Humanity";
		public const String Template_Models_Enumerations_ThemesAvailable_Le_Frog = "Template_Models_Enumerations_ThemesAvailable_Le_Frog";
		public const String Template_Models_Enumerations_ThemesAvailable_Mint_Choc = "Template_Models_Enumerations_ThemesAvailable_Mint_Choc";
		public const String Template_Models_Enumerations_ThemesAvailable_Overcast = "Template_Models_Enumerations_ThemesAvailable_Overcast";
		public const String Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder = "Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder";
		public const String Template_Models_Enumerations_ThemesAvailable_Redmond = "Template_Models_Enumerations_ThemesAvailable_Redmond";
		public const String Template_Models_Enumerations_ThemesAvailable_Smoothness = "Template_Models_Enumerations_ThemesAvailable_Smoothness";
		public const String Template_Models_Enumerations_ThemesAvailable_South_Street = "Template_Models_Enumerations_ThemesAvailable_South_Street";
		public const String Template_Models_Enumerations_ThemesAvailable_Start = "Template_Models_Enumerations_ThemesAvailable_Start";
		public const String Template_Models_Enumerations_ThemesAvailable_Sunny = "Template_Models_Enumerations_ThemesAvailable_Sunny";
		public const String Template_Models_Enumerations_ThemesAvailable_Swanky_Purse = "Template_Models_Enumerations_ThemesAvailable_Swanky_Purse";
		public const String Template_Models_Enumerations_ThemesAvailable_Trontastic = "Template_Models_Enumerations_ThemesAvailable_Trontastic";
		public const String Template_Models_Enumerations_ThemesAvailable_UI_Darkness = "Template_Models_Enumerations_ThemesAvailable_UI_Darkness";
		public const String Template_Models_Enumerations_ThemesAvailable_UI_Lightness = "Template_Models_Enumerations_ThemesAvailable_UI_Lightness";
		public const String Template_Models_Enumerations_ThemesAvailable_Vader = "Template_Models_Enumerations_ThemesAvailable_Vader";
		public const String Template_Models_Enumerations_Gender_Female = "Template_Models_Enumerations_Gender_Female";
		public const String Template_Models_Enumerations_Gender_Male = "Template_Models_Enumerations_Gender_Male";
		public const String Template_Models_Enumerations_Gender_Other = "Template_Models_Enumerations_Gender_Other";
		public const String Template_Models_Enumerations_SiteRoles_Administrator = "Template_Models_Enumerations_SiteRoles_Administrator";
		public const String Template_Models_Enumerations_SiteRoles_Guest = "Template_Models_Enumerations_SiteRoles_Guest";
		public const String Template_Models_Enumerations_CulturesAvailable_en_US = "Template_Models_Enumerations_CulturesAvailable_en_US";
		public const String Template_Models_Enumerations_CulturesAvailable_es_ES = "Template_Models_Enumerations_CulturesAvailable_es_ES";
	}
	public class EnumerationsTextsViewModelHelper
	{
		public  string Template_Models_Enumerations_ThemesAvailable_Base {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Base;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Black_Tie {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Black_Tie;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Blitzer {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Blitzer;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Cupertino {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Cupertino;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Dark_Hive {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Dark_Hive;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Dot_Luv {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Dot_Luv;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Eggplant {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Eggplant;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Excite_Bike {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Excite_Bike;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Flick {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Flick;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Humanity {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Humanity;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Le_Frog {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Le_Frog;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Mint_Choc {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Mint_Choc;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Overcast {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Overcast;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Redmond {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Redmond;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Smoothness {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Smoothness;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_South_Street {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_South_Street;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Start {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Start;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Sunny {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Sunny;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Swanky_Purse {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Swanky_Purse;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Trontastic {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Trontastic;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_UI_Darkness {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_UI_Darkness;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_UI_Lightness {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_UI_Lightness;	}	}
		public  string Template_Models_Enumerations_ThemesAvailable_Vader {	get{	return EnumerationsTexts.Template_Models_Enumerations_ThemesAvailable_Vader;	}	}
		public  string Template_Models_Enumerations_Gender_Female {	get{	return EnumerationsTexts.Template_Models_Enumerations_Gender_Female;	}	}
		public  string Template_Models_Enumerations_Gender_Male {	get{	return EnumerationsTexts.Template_Models_Enumerations_Gender_Male;	}	}
		public  string Template_Models_Enumerations_Gender_Other {	get{	return EnumerationsTexts.Template_Models_Enumerations_Gender_Other;	}	}
		public  string Template_Models_Enumerations_SiteRoles_Administrator {	get{	return EnumerationsTexts.Template_Models_Enumerations_SiteRoles_Administrator;	}	}
		public  string Template_Models_Enumerations_SiteRoles_Guest {	get{	return EnumerationsTexts.Template_Models_Enumerations_SiteRoles_Guest;	}	}
		public  string Template_Models_Enumerations_CulturesAvailable_en_US {	get{	return EnumerationsTexts.Template_Models_Enumerations_CulturesAvailable_en_US;	}	}
		public  string Template_Models_Enumerations_CulturesAvailable_es_ES {	get{	return EnumerationsTexts.Template_Models_Enumerations_CulturesAvailable_es_ES;	}	}
	}
	public class GeneralTextsKeys
	{
		public const String About = "About";
		public const String Blog = "Blog";
		public const String BreadcrumbNavigation = "BreadcrumbNavigation";
		public const String Dashboard = "Dashboard";
		public const String Documentation = "Documentation";
		public const String Home = "Home";
		public const String Languages = "Languages";
		public const String LogOff = "LogOff";
		public const String LogOn = "LogOn";
		public const String LogViewer = "LogViewer";
		public const String MenuSite = "MenuSite";
		public const String NoDataFound = "NoDataFound";
		public const String NotFound404 = "NotFound404";
		public const String OnlineSince = "OnlineSince";
		public const String PermissionDenied = "PermissionDenied";
		public const String PleaseReviewForm = "PleaseReviewForm";
		public const String Preferences = "Preferences";
		public const String Required = "Required";
		public const String SelectListenerToGetDetails = "SelectListenerToGetDetails";
		public const String SelectSourceToGetDetails = "SelectSourceToGetDetails";
		public const String SessionExpired = "SessionExpired";
		public const String SessionExpiredPleaseLogin = "SessionExpiredPleaseLogin";
		public const String Showing = "Showing";
		public const String SiteAdmin = "SiteAdmin";
		public const String SiteThemes = "SiteThemes";
		public const String TotalRecordsFound = "TotalRecordsFound";
		public const String TraceDataSource = "TraceDataSource";
		public const String UnAuthorizedError = "UnAuthorizedError";
		public const String UnAuthorizedError_TryLoginAsDifferentUser = "UnAuthorizedError_TryLoginAsDifferentUser";
		public const String UnexpectedCommunicationError = "UnexpectedCommunicationError";
		public const String UnexpectedError = "UnexpectedError";
		public const String UnexpectedErrorIdAssigned = "UnexpectedErrorIdAssigned";
		public const String Update = "Update";
		public const String User = "User";
		public const String UserAdmin = "UserAdmin";
		public const String Validate = "Validate";
		public const String Version = "Version";
	}
	public class GeneralTextsViewModelHelper
	{
		public  string About {	get{	return GeneralTexts.About;	}	}
		public  string Blog {	get{	return GeneralTexts.Blog;	}	}
		public  string BreadcrumbNavigation {	get{	return GeneralTexts.BreadcrumbNavigation;	}	}
		public  string Dashboard {	get{	return GeneralTexts.Dashboard;	}	}
		public  string Documentation {	get{	return GeneralTexts.Documentation;	}	}
		public  string Home {	get{	return GeneralTexts.Home;	}	}
		public  string Languages {	get{	return GeneralTexts.Languages;	}	}
		public  string LogOff {	get{	return GeneralTexts.LogOff;	}	}
		public  string LogOn {	get{	return GeneralTexts.LogOn;	}	}
		public  string LogViewer {	get{	return GeneralTexts.LogViewer;	}	}
		public  string MenuSite {	get{	return GeneralTexts.MenuSite;	}	}
		public  string NoDataFound {	get{	return GeneralTexts.NoDataFound;	}	}
		public  string NotFound404 {	get{	return GeneralTexts.NotFound404;	}	}
		public  string OnlineSince {	get{	return GeneralTexts.OnlineSince;	}	}
		public  string PermissionDenied {	get{	return GeneralTexts.PermissionDenied;	}	}
		public  string PleaseReviewForm {	get{	return GeneralTexts.PleaseReviewForm;	}	}
		public  string Preferences {	get{	return GeneralTexts.Preferences;	}	}
		public  string Required {	get{	return GeneralTexts.Required;	}	}
		public  string SelectListenerToGetDetails {	get{	return GeneralTexts.SelectListenerToGetDetails;	}	}
		public  string SelectSourceToGetDetails {	get{	return GeneralTexts.SelectSourceToGetDetails;	}	}
		public  string SessionExpired {	get{	return GeneralTexts.SessionExpired;	}	}
		public  string SessionExpiredPleaseLogin {	get{	return GeneralTexts.SessionExpiredPleaseLogin;	}	}
		public  string Showing {	get{	return GeneralTexts.Showing;	}	}
		public  string SiteAdmin {	get{	return GeneralTexts.SiteAdmin;	}	}
		public  string SiteThemes {	get{	return GeneralTexts.SiteThemes;	}	}
		public  string TotalRecordsFound {	get{	return GeneralTexts.TotalRecordsFound;	}	}
		public  string TraceDataSource {	get{	return GeneralTexts.TraceDataSource;	}	}
		public  string UnAuthorizedError {	get{	return GeneralTexts.UnAuthorizedError;	}	}
		public  string UnAuthorizedError_TryLoginAsDifferentUser {	get{	return GeneralTexts.UnAuthorizedError_TryLoginAsDifferentUser;	}	}
		public  string UnexpectedCommunicationError {	get{	return GeneralTexts.UnexpectedCommunicationError;	}	}
		public  string UnexpectedError {	get{	return GeneralTexts.UnexpectedError;	}	}
		public  string UnexpectedErrorIdAssigned {	get{	return GeneralTexts.UnexpectedErrorIdAssigned;	}	}
		public  string Update {	get{	return GeneralTexts.Update;	}	}
		public  string User {	get{	return GeneralTexts.User;	}	}
		public  string UserAdmin {	get{	return GeneralTexts.UserAdmin;	}	}
		public  string Validate {	get{	return GeneralTexts.Validate;	}	}
		public  string Version {	get{	return GeneralTexts.Version;	}	}
	}
	public class JavascriptTextsKeys
	{
		public const String accept = "accept";
		public const String cancel = "cancel";
		public const String clickToPickDate = "clickToPickDate";
		public const String close = "close";
		public const String confirmToContinue = "confirmToContinue";
		public const String email = "email";
		public const String emailFormatNotValid = "emailFormatNotValid";
		public const String errorsInForm = "errorsInForm";
		public const String mandatoryField = "mandatoryField";
		public const String minLengthIs = "minLengthIs";
		public const String noResultsFound = "noResultsFound";
		public const String password = "password";
		public const String passwordsDoNotMatch = "passwordsDoNotMatch";
		public const String siteTitle = "siteTitle";
		public const String unExpectedError = "unExpectedError";
		public const String userName = "userName";
		public const String validate = "validate";
	}
	public class JavascriptTextsViewModelHelper
	{
		public  string accept {	get{	return JavascriptTexts.accept;	}	}
		public  string cancel {	get{	return JavascriptTexts.cancel;	}	}
		public  string clickToPickDate {	get{	return JavascriptTexts.clickToPickDate;	}	}
		public  string close {	get{	return JavascriptTexts.close;	}	}
		public  string confirmToContinue {	get{	return JavascriptTexts.confirmToContinue;	}	}
		public  string email {	get{	return JavascriptTexts.email;	}	}
		public  string emailFormatNotValid {	get{	return JavascriptTexts.emailFormatNotValid;	}	}
		public  string errorsInForm {	get{	return JavascriptTexts.errorsInForm;	}	}
		public  string mandatoryField {	get{	return JavascriptTexts.mandatoryField;	}	}
		public  string minLengthIs {	get{	return JavascriptTexts.minLengthIs;	}	}
		public  string noResultsFound {	get{	return JavascriptTexts.noResultsFound;	}	}
		public  string password {	get{	return JavascriptTexts.password;	}	}
		public  string passwordsDoNotMatch {	get{	return JavascriptTexts.passwordsDoNotMatch;	}	}
		public  string siteTitle {	get{	return JavascriptTexts.siteTitle;	}	}
		public  string unExpectedError {	get{	return JavascriptTexts.unExpectedError;	}	}
		public  string userName {	get{	return JavascriptTexts.userName;	}	}
		public  string validate {	get{	return JavascriptTexts.validate;	}	}
	}
	public class UserAdminTextsKeys
	{
		public const String Account = "Account";
		public const String Add = "Add";
		public const String ApproveAccount = "ApproveAccount";
		public const String Approved = "Approved";
		public const String ChangePassword = "ChangePassword";
		public const String Comments = "Comments";
		public const String Confirm = "Confirm";
		public const String Created = "Created";
		public const String CreationDate = "CreationDate";
		public const String CreationDateFrom = "CreationDateFrom";
		public const String CreationDateTo = "CreationDateTo";
		public const String CreationDateToGreaterThanFrom = "CreationDateToGreaterThanFrom";
		public const String DeleteAccount = "DeleteAccount";
		public const String Details = "Details";
		public const String Email = "Email";
		public const String EmailAddress = "EmailAddress";
		public const String EmailAddressInvalid = "EmailAddressInvalid";
		public const String EmailAndComments = "EmailAndComments";
		public const String FilterByRoleName = "FilterByRoleName";
		public const String IsOnline = "IsOnline";
		public const String LastActive = "LastActive";
		public const String LastActivity = "LastActivity";
		public const String LastChanged = "LastChanged";
		public const String LastLockOut = "LastLockOut";
		public const String LastLogin = "LastLogin";
		public const String LastPasswordChange = "LastPasswordChange";
		public const String Locked = "Locked";
		public const String LockedOutSince = "LockedOutSince";
		public const String ManagePassword = "ManagePassword";
		public const String ManageUserRoles = "ManageUserRoles";
		public const String Never = "Never";
		public const String NewPassword = "NewPassword";
		public const String NoPasswordQuestionDefined = "NoPasswordQuestionDefined";
		public const String OldPassword = "OldPassword";
		public const String Password = "Password";
		public const String PasswordAnswer = "PasswordAnswer";
		public const String PasswordChangeAndSetLiteral = "PasswordChangeAndSetLiteral";
		public const String PasswordCouldNotChangedLiteral = "PasswordCouldNotChangedLiteral";
		public const String PasswordQuestion = "PasswordQuestion";
		public const String ResetRandomPasswordEmailUser = "ResetRandomPasswordEmailUser";
		public const String RoleCreate = "RoleCreate";
		public const String Roles = "Roles";
		public const String SaveComments = "SaveComments";
		public const String Search = "Search";
		public const String UnApproveAccount = "UnApproveAccount";
		public const String UserCouldNotBeUnlocked = "UserCouldNotBeUnlocked";
		public const String UserDeleted = "UserDeleted";
		public const String UserDetails = "UserDetails";
		public const String UserName = "UserName";
		public const String UserRoles = "UserRoles";
		public const String Users = "Users";
		public const String UserSaved = "UserSaved";
		public const String UsersFilter = "UsersFilter";
		public const String UsersFilterError = "UsersFilterError";
		public const String UsersInRole = "UsersInRole";
		public const String DuplicateEmail = "DuplicateEmail";
		public const String DuplicateUserName = "DuplicateUserName";
		public const String InvalidAnswer = "InvalidAnswer";
		public const String InvalidEmail = "InvalidEmail";
		public const String InvalidPassword = "InvalidPassword";
		public const String InvalidQuestion = "InvalidQuestion";
		public const String InvalidUserName = "InvalidUserName";
		public const String ResetPasswordMailBody = "ResetPasswordMailBody";
		public const String ResetPasswordMailSubject = "ResetPasswordMailSubject";
		public const String UserSearch = "UserSearch";
		public const String UserIsAlreadyInRole = "UserIsAlreadyInRole";
		public const String RoleAlreadyExists = "RoleAlreadyExists";
		public const String RoleHasPendingUsersError = "RoleHasPendingUsersError";
		public const String RoleUnexists = "RoleUnexists";
		public const String UsersNotFound = "UsersNotFound";
		public const String UserInfo = "UserInfo";
		public const String UserStatus = "UserStatus";
		public const String Offline = "Offline";
		public const String Online = "Online";
		public const String Unapproved = "Unapproved";
		public const String RolesUpdate = "RolesUpdate";
		public const String UserRolesNeeded = "UserRolesNeeded";
		public const String UserNotFound = "UserNotFound";
		public const String UserAccountActivated = "UserAccountActivated";
		public const String ActivationTokenExpired = "ActivationTokenExpired";
		public const String UserUnlocked = "UserUnlocked";
		public const String UnLockUser = "UnLockUser";
	}
	public class UserAdminTextsViewModelHelper
	{
		public  string Account {	get{	return UserAdminTexts.Account;	}	}
		public  string Add {	get{	return UserAdminTexts.Add;	}	}
		public  string ApproveAccount {	get{	return UserAdminTexts.ApproveAccount;	}	}
		public  string Approved {	get{	return UserAdminTexts.Approved;	}	}
		public  string ChangePassword {	get{	return UserAdminTexts.ChangePassword;	}	}
		public  string Comments {	get{	return UserAdminTexts.Comments;	}	}
		public  string Confirm {	get{	return UserAdminTexts.Confirm;	}	}
		public  string Created {	get{	return UserAdminTexts.Created;	}	}
		public  string CreationDate {	get{	return UserAdminTexts.CreationDate;	}	}
		public  string CreationDateFrom {	get{	return UserAdminTexts.CreationDateFrom;	}	}
		public  string CreationDateTo {	get{	return UserAdminTexts.CreationDateTo;	}	}
		public  string CreationDateToGreaterThanFrom {	get{	return UserAdminTexts.CreationDateToGreaterThanFrom;	}	}
		public  string DeleteAccount {	get{	return UserAdminTexts.DeleteAccount;	}	}
		public  string Details {	get{	return UserAdminTexts.Details;	}	}
		public  string Email {	get{	return UserAdminTexts.Email;	}	}
		public  string EmailAddress {	get{	return UserAdminTexts.EmailAddress;	}	}
		public  string EmailAddressInvalid {	get{	return UserAdminTexts.EmailAddressInvalid;	}	}
		public  string EmailAndComments {	get{	return UserAdminTexts.EmailAndComments;	}	}
		public  string FilterByRoleName {	get{	return UserAdminTexts.FilterByRoleName;	}	}
		public  string IsOnline {	get{	return UserAdminTexts.IsOnline;	}	}
		public  string LastActive {	get{	return UserAdminTexts.LastActive;	}	}
		public  string LastActivity {	get{	return UserAdminTexts.LastActivity;	}	}
		public  string LastChanged {	get{	return UserAdminTexts.LastChanged;	}	}
		public  string LastLockOut {	get{	return UserAdminTexts.LastLockOut;	}	}
		public  string LastLogin {	get{	return UserAdminTexts.LastLogin;	}	}
		public  string LastPasswordChange {	get{	return UserAdminTexts.LastPasswordChange;	}	}
		public  string Locked {	get{	return UserAdminTexts.Locked;	}	}
		public  string LockedOutSince {	get{	return UserAdminTexts.LockedOutSince;	}	}
		public  string ManagePassword {	get{	return UserAdminTexts.ManagePassword;	}	}
		public  string ManageUserRoles {	get{	return UserAdminTexts.ManageUserRoles;	}	}
		public  string Never {	get{	return UserAdminTexts.Never;	}	}
		public  string NewPassword {	get{	return UserAdminTexts.NewPassword;	}	}
		public  string NoPasswordQuestionDefined {	get{	return UserAdminTexts.NoPasswordQuestionDefined;	}	}
		public  string OldPassword {	get{	return UserAdminTexts.OldPassword;	}	}
		public  string Password {	get{	return UserAdminTexts.Password;	}	}
		public  string PasswordAnswer {	get{	return UserAdminTexts.PasswordAnswer;	}	}
		public  string PasswordChangeAndSetLiteral {	get{	return UserAdminTexts.PasswordChangeAndSetLiteral;	}	}
		public  string PasswordCouldNotChangedLiteral {	get{	return UserAdminTexts.PasswordCouldNotChangedLiteral;	}	}
		public  string PasswordQuestion {	get{	return UserAdminTexts.PasswordQuestion;	}	}
		public  string ResetRandomPasswordEmailUser {	get{	return UserAdminTexts.ResetRandomPasswordEmailUser;	}	}
		public  string RoleCreate {	get{	return UserAdminTexts.RoleCreate;	}	}
		public  string Roles {	get{	return UserAdminTexts.Roles;	}	}
		public  string SaveComments {	get{	return UserAdminTexts.SaveComments;	}	}
		public  string Search {	get{	return UserAdminTexts.Search;	}	}
		public  string UnApproveAccount {	get{	return UserAdminTexts.UnApproveAccount;	}	}
		public  string UserCouldNotBeUnlocked {	get{	return UserAdminTexts.UserCouldNotBeUnlocked;	}	}
		public  string UserDeleted {	get{	return UserAdminTexts.UserDeleted;	}	}
		public  string UserDetails {	get{	return UserAdminTexts.UserDetails;	}	}
		public  string UserName {	get{	return UserAdminTexts.UserName;	}	}
		public  string UserRoles {	get{	return UserAdminTexts.UserRoles;	}	}
		public  string Users {	get{	return UserAdminTexts.Users;	}	}
		public  string UserSaved {	get{	return UserAdminTexts.UserSaved;	}	}
		public  string UsersFilter {	get{	return UserAdminTexts.UsersFilter;	}	}
		public  string UsersFilterError {	get{	return UserAdminTexts.UsersFilterError;	}	}
		public  string UsersInRole {	get{	return UserAdminTexts.UsersInRole;	}	}
		public  string DuplicateEmail {	get{	return UserAdminTexts.DuplicateEmail;	}	}
		public  string DuplicateUserName {	get{	return UserAdminTexts.DuplicateUserName;	}	}
		public  string InvalidAnswer {	get{	return UserAdminTexts.InvalidAnswer;	}	}
		public  string InvalidEmail {	get{	return UserAdminTexts.InvalidEmail;	}	}
		public  string InvalidPassword {	get{	return UserAdminTexts.InvalidPassword;	}	}
		public  string InvalidQuestion {	get{	return UserAdminTexts.InvalidQuestion;	}	}
		public  string InvalidUserName {	get{	return UserAdminTexts.InvalidUserName;	}	}
		public  string ResetPasswordMailBody {	get{	return UserAdminTexts.ResetPasswordMailBody;	}	}
		public  string ResetPasswordMailSubject {	get{	return UserAdminTexts.ResetPasswordMailSubject;	}	}
		public  string UserSearch {	get{	return UserAdminTexts.UserSearch;	}	}
		public  string UserIsAlreadyInRole {	get{	return UserAdminTexts.UserIsAlreadyInRole;	}	}
		public  string RoleAlreadyExists {	get{	return UserAdminTexts.RoleAlreadyExists;	}	}
		public  string RoleHasPendingUsersError {	get{	return UserAdminTexts.RoleHasPendingUsersError;	}	}
		public  string RoleUnexists {	get{	return UserAdminTexts.RoleUnexists;	}	}
		public  string UsersNotFound {	get{	return UserAdminTexts.UsersNotFound;	}	}
		public  string UserInfo {	get{	return UserAdminTexts.UserInfo;	}	}
		public  string UserStatus {	get{	return UserAdminTexts.UserStatus;	}	}
		public  string Offline {	get{	return UserAdminTexts.Offline;	}	}
		public  string Online {	get{	return UserAdminTexts.Online;	}	}
		public  string Unapproved {	get{	return UserAdminTexts.Unapproved;	}	}
		public  string RolesUpdate {	get{	return UserAdminTexts.RolesUpdate;	}	}
		public  string UserRolesNeeded {	get{	return UserAdminTexts.UserRolesNeeded;	}	}
		public  string UserNotFound {	get{	return UserAdminTexts.UserNotFound;	}	}
		public  string UserAccountActivated {	get{	return UserAdminTexts.UserAccountActivated;	}	}
		public  string ActivationTokenExpired {	get{	return UserAdminTexts.ActivationTokenExpired;	}	}
		public  string UserUnlocked {	get{	return UserAdminTexts.UserUnlocked;	}	}
		public  string UnLockUser {	get{	return UserAdminTexts.UnLockUser;	}	}
	}
	public class UserProfileTextsKeys
	{
		public const String BirtDate = "BirtDate";
		public const String FirstName = "FirstName";
		public const String Gender = "Gender";
		public const String Language = "Language";
		public const String LastName = "LastName";
		public const String Theme = "Theme";
	}
	public class UserProfileTextsViewModelHelper
	{
		public  string BirtDate {	get{	return UserProfileTexts.BirtDate;	}	}
		public  string FirstName {	get{	return UserProfileTexts.FirstName;	}	}
		public  string Gender {	get{	return UserProfileTexts.Gender;	}	}
		public  string Language {	get{	return UserProfileTexts.Language;	}	}
		public  string LastName {	get{	return UserProfileTexts.LastName;	}	}
		public  string Theme {	get{	return UserProfileTexts.Theme;	}	}
	}
}
