//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Enumerations
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumerationsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumerationsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Enumerations.EnumerationsTexts", typeof(EnumerationsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (USA).
        /// </summary>
        public static string Template_Models_Enumerations_CulturesAvailable_en_US {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_CulturesAvailable_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Template_Models_Enumerations_CulturesAvailable_es_ES {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_CulturesAvailable_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Template_Models_Enumerations_Gender_Female {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Template_Models_Enumerations_Gender_Male {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Template_Models_Enumerations_Gender_Other {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Template_Models_Enumerations_SiteRoles_Administrator {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_SiteRoles_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Template_Models_Enumerations_SiteRoles_Guest {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_SiteRoles_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Base {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black_Tie.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Black_Tie {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Black_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzer.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Blitzer {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Blitzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupertino.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Cupertino {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Cupertino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Hive.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Dark_Hive {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Dark_Hive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Luv.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Dot_Luv {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Dot_Luv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggplant.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Eggplant {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Eggplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excite Bike.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Excite_Bike {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Excite_Bike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Flick {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Flick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Sneaks.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Hot_Sneaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanity.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Humanity {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Humanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Frog.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Le_Frog {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Le_Frog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mint Choc.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Mint_Choc {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Mint_Choc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Overcast {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepper Grinder.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Pepper_Grinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmond.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Redmond {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Redmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothness.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Smoothness {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Smoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Street.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_South_Street {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_South_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Start {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Sunny {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swanky Purse.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Swanky_Purse {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Swanky_Purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trontastic.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Trontastic {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Trontastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Darkness.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_UI_Darkness {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_UI_Darkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Lightness.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_UI_Lightness {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_UI_Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vader.
        /// </summary>
        public static string Template_Models_Enumerations_ThemesAvailable_Vader {
            get {
                return ResourceManager.GetString("Template_Models_Enumerations_ThemesAvailable_Vader", resourceCulture);
            }
        }
    }
}
