//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormsWizardGeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsWizardGeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wizard.FormsWizardGeneralResources", typeof(FormsWizardGeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and transforming {0} project.
        /// </summary>
        public static string AddingProject {
            get {
                return ResourceManager.GetString("AddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create database later at &quot;/DAL/Scripts/InstallDatabaseDefault.cmd&quot;.
        /// </summary>
        public static string DatabaseCreateLaterHow {
            get {
                return ResourceManager.GetString("DatabaseCreateLaterHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create database now ?.
        /// </summary>
        public static string DatabaseCreateNow {
            get {
                return ResourceManager.GetString("DatabaseCreateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Startup Projects.
        /// </summary>
        public static string SettingStartupProjects {
            get {
                return ResourceManager.GetString("SettingStartupProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error ocurred. Get more information at &quot;{0}&quot;.
        /// </summary>
        public static string UnHandledErrorMoreInfo {
            get {
                return ResourceManager.GetString("UnHandledErrorMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTier MVC Application Wizard.
        /// </summary>
        public static string WizardCaption {
            get {
                return ResourceManager.GetString("WizardCaption", resourceCulture);
            }
        }
    }
}
