//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $customNamespace$.Resources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$customNamespace$.Resources.General.GeneralTexts", typeof(GeneralTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadcrumb navigation.
        /// </summary>
        public static string BreadcrumbNavigation {
            get {
                return ResourceManager.GetString("BreadcrumbNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date pattern.
        /// </summary>
        public static string DatePattern {
            get {
                return ResourceManager.GetString("DatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    This web site was created using &lt;a href=&quot;https://github.com/jordivila/Net_MVC_NLayer_Generator&quot;&gt;Net_MVC_NLayer_Generator&lt;/a&gt;.
        ///    The template allows you to create a Visual Studio 2013 solution based on 2 possibilities:
        ///    &lt;ul class=&quot;ui-list&quot;&gt;
        ///        &lt;li&gt;an ASP NET MVC web site&lt;/li&gt;
        ///        &lt;li&gt;a .NET Multi-Tier application with an ASP NET MVC front-end website and WCF back-end application&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///
        ///    The resulting solution can be desployed to Azure Web Sites or Azure Cloud Service [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeIndexText {
            get {
                return ResourceManager.GetString("HomeIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open menu.
        /// </summary>
        public static string MenuSite {
            get {
                return ResourceManager.GetString("MenuSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information was found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not found.
        /// </summary>
        public static string NotFound404 {
            get {
                return ResourceManager.GetString("NotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online since.
        /// </summary>
        public static string OnlineSince {
            get {
                return ResourceManager.GetString("OnlineSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, review your form.
        /// </summary>
        public static string PleaseReviewForm {
            get {
                return ResourceManager.GetString("PleaseReviewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select listener type to see details.
        /// </summary>
        public static string SelectListenerToGetDetails {
            get {
                return ResourceManager.GetString("SelectListenerToGetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source name to get details.
        /// </summary>
        public static string SelectSourceToGetDetails {
            get {
                return ResourceManager.GetString("SelectSourceToGetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired, please login.
        /// </summary>
        public static string SessionExpiredPleaseLogin {
            get {
                return ResourceManager.GetString("SessionExpiredPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Admin.
        /// </summary>
        public static string SiteAdmin {
            get {
                return ResourceManager.GetString("SiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site themes.
        /// </summary>
        public static string SiteThemes {
            get {
                return ResourceManager.GetString("SiteThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number.
        /// </summary>
        public static string TheNumber {
            get {
                return ResourceManager.GetString("TheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number formatted as currency.
        /// </summary>
        public static string TheNumberFormattedAsCurrency {
            get {
                return ResourceManager.GetString("TheNumberFormattedAsCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number formatted as number.
        /// </summary>
        public static string TheNumberFormattedAsNumber {
            get {
                return ResourceManager.GetString("TheNumberFormattedAsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is....
        /// </summary>
        public static string TodayIs {
            get {
                return ResourceManager.GetString("TodayIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount is.
        /// </summary>
        public static string TotalAmountIs {
            get {
                return ResourceManager.GetString("TotalAmountIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total records found.
        /// </summary>
        public static string TotalRecordsFound {
            get {
                return ResourceManager.GetString("TotalRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Data Source.
        /// </summary>
        public static string TraceDataSource {
            get {
                return ResourceManager.GetString("TraceDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string UnAuthorizedError {
            get {
                return ResourceManager.GetString("UnAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try logging in as a different user.
        /// </summary>
        public static string UnAuthorizedError_TryLoginAsDifferentUser {
            get {
                return ResourceManager.GetString("UnAuthorizedError_TryLoginAsDifferentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to communicate with data servers.
        /// </summary>
        public static string UnexpectedCommunicationError {
            get {
                return ResourceManager.GetString("UnexpectedCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier has been assigned to this error:.
        /// </summary>
        public static string UnexpectedErrorIdAssigned {
            get {
                return ResourceManager.GetString("UnexpectedErrorIdAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}